# translation of src_debug_server.po to French
# Module src_debug_server translation file for language=en
# Copyright (C) 2003 Archaeopteryx Software, Inc.
# Wing Python IDE -- wingware.com
# Encolpe DEGOUTE <encolpe.degoute@free.fr>, 2004.
#
msgid ""
msgstr ""
"Project-Id-Version: src_debug_server\n"
"POT-Creation-Date: 2018-08-23 14:16+EDT\n"
"PO-Revision-Date: 2018-08-25 23:20+0200\n"
"Last-Translator: Jean Sanchez <js.fr@protonmail.ch>\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.4\n"
"X-Generator: Poedit 2.1.1\n"

#: src/debug/tserver/abstract.py:331
msgid "Wing Debug Log File\n"
msgstr "Fichier de log de débogage de Wing\n"

#: src/debug/tserver/abstract.py:332
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Ce file peut être utilisé pour diagnostiquer les problèmes dans les routines "
"du débogueur\n"

#: src/debug/tserver/abstract.py:333
msgid "For help, contact support@wingware.com\n"
msgstr "Pour de l'aide, contactez support@wingware.com\n"

#: src/debug/tserver/abstract.py:338
msgid "Warning:  Log file does not exist:\n"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/abstract.py:340
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Avertissement : et ne peut pas être créé. Enregistrement désactivé.\n"

#: src/debug/tserver/abstract.py:343
msgid "Warning:  Log file is not a file:\n"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/abstract.py:345
msgid "Warning:  Logging disabled\n"
msgstr "Avertissement : Logging désactivé\n"

#: src/debug/tserver/dbginspect.py:54 src/debug/tserver/dbgserver.py:2942
#: src/debug/tserver/dbgutils.py:487 src/debug/tserver/dbgutils.py:507
msgid "(truncated)"
msgstr "(tronqué)"

#: src/debug/tserver/dbginspect.py:910 src/debug/tserver/dbgutils.py:495
#: src/debug/tserver/dbgutils.py:517 src/debug/tserver/dbgutils.py:3069
msgid "<opaque "
msgstr "<opaque "

#: src/debug/tserver/dbgserver.py:1183
msgid "<module>"
msgstr "<module>"

#: src/debug/tserver/dbgserver.py:1331
msgid "<error evaluating>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgserver.py:1923 src/debug/tserver/dbgserver.py:1959
msgid "<thread %i is running>"
msgstr "<la tâche %i est en cours>"

#: src/debug/tserver/dbgserver.py:1926 src/debug/tserver/dbgserver.py:1962
msgid "<invalid thread id %s or stack index %s>"
msgstr "<id de tâche %s ou index de pile %s invalide>"

#: src/debug/tserver/dbgserver.py:1928 src/debug/tserver/dbgserver.py:1964
msgid "<invalid stack frame>"
msgstr "<élément de pile invalide>"

#: src/debug/tserver/dbgserver.py:1992 src/debug/tserver/dbgserver.py:2021
msgid "<sys.modules does not exist>"
msgstr "<sys.modules n'existe pas>"

#: src/debug/tserver/dbgserver.py:1995 src/debug/tserver/dbgserver.py:2027
msgid "<error accessing sys.modules>"
msgstr "<erreur en accédant à sys.modules>"

#: src/debug/tserver/dbgserver.py:2024
msgid "<no longer exists"
msgstr "<n'existe plus"

#: src/debug/tserver/dbgserver.py:2072 src/debug/tserver/dbgserver.py:2125
msgid "<no longer exists>"
msgstr "<n'existe plus>"

#: src/debug/tserver/dbgserver.py:2103 src/debug/tserver/dbgserver.py:4183
msgid "<parent too large>"
msgstr "<parent trop large>"

#: src/debug/tserver/dbgserver.py:2105 src/debug/tserver/dbgserver.py:4185
msgid "<invalid parent type>"
msgstr "<type de parent invalide>"

#: src/debug/tserver/dbgserver.py:2115 src/debug/tserver/dbgserver.py:2579
msgid "<value not found>"
msgstr "<valuer non trouvée>"

#: src/debug/tserver/dbgserver.py:2567
msgid "<thread is running>"
msgstr "<tâche en cours>"

#: src/debug/tserver/dbgserver.py:2569
msgid "<invalid context>"
msgstr "<contexte invalide>"

#: src/debug/tserver/dbgserver.py:4191
msgid "<invalid path %s at pos=%i>"
msgstr "<chemin %s invalide à la position=%i>"

#: src/debug/tserver/dbgutils.py:151
msgid "<undefined>"
msgstr "<indéfini>"

#: src/debug/tserver/dbgutils.py:167
msgid "at"
msgstr "à"

#: src/debug/tserver/dbgutils.py:177
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:187 src/debug/tserver/dbgutils.py:2571
#, fuzzy
msgid "<error handling value>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgutils.py:189
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:197
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:217
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:234
msgid "<opaque"
msgstr "<opaque"

#: src/debug/tserver/dbgutils.py:509
msgid "<huge %s at %s; len=%i>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbgutils.py:697 src/debug/tserver/dbgutils.py:709
msgid ", pos "
msgstr ", position "

#: src/debug/tserver/dbgutils.py:713
msgid ", line "
msgstr ", ligne "

#: src/debug/tserver/dbgutils.py:715
msgid "SyntaxError: "
msgstr "Erreur de syntaxe : "

#: src/debug/tserver/dbgutils.py:743
msgid "Error"
msgstr "Erreur"

#: src/debug/tserver/dbgutils.py:751
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Erreur : Wing n'a pas été capable de générer un message d'exception"

#: src/debug/tserver/dbgutils.py:3383 src/debug/tserver/dbgutils.py:3399
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3383 src/debug/tserver/dbgutils.py:3399
msgid "Value"
msgstr "Valeur"

#: src/debug/tserver/dbgutils.py:3394 src/debug/tserver/dbgutils.py:3421
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:459
msgid "Redirected I/O failed on closed debug connection"
msgstr ""
"La redirection des E/S a échoué lors de la fermeture de la connexion de "
"débogage"

#: src/debug/tserver/netserver.py:613
msgid "EOF when reading a line"
msgstr "EOF lors de la lecture d'une ligne"

#: src/debug/tserver/netserver.py:1110
msgid "(unavailable)"
msgstr "(indisponible)"

#: src/debug/tserver/netserver.py:1366
msgid "[omitting some output]"
msgstr "[omet quelques sorties]"

#: src/debug/tserver/startdebug.py:195 src/debug/tserver/startdebug.py:373
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/startdebug.py:199 src/debug/tserver/startdebug.py:377
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/startdebug.py:426
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:427
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:428
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:442
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:464
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:475
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:635
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:636
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:637
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:717 src/debug/tserver/startdebug.py:719
msgid "-- Type return or enter to exit --\n"
msgstr ""

#~ msgid "<unknown type>"
#~ msgstr "<type inconnu>"

#~ msgid "Value too large to evaluate: "
#~ msgstr "Value trop grande pour être évaluée : "

#~ msgid "<invalid path registration>"
#~ msgstr "<enregistrement de chemin invalide>"

#~ msgid "Function"
#~ msgstr "Fonction"

#~ msgid "Method"
#~ msgstr "Méthode"

#, fuzzy
#~ msgid "Could not execute because an error occurred:\n"
#~ msgstr ""
#~ "Impossible de lancer le programme car il y a eu une erreur:\n"
#~ "\n"

#~ msgid "Error: Runtime exception occurred"
#~ msgstr "Erreur: Obtention d'une erreur d'exécution"

#~ msgid "Default User"
#~ msgstr "Utilisateur par défaut"
