# translation of src_debug_server.po to French
# Module src_debug_server translation file for language=en
# Copyright (C) 2003 Archaeopteryx Software, Inc.
# Wing Python IDE -- wingware.com
# Encolpe DEGOUTE <encolpe.degoute@free.fr>, 2004.
#
msgid ""
msgstr ""
"Project-Id-Version: src_debug_server\n"
"POT-Creation-Date: 2018-03-21 10:16+EDT\n"
"PO-Revision-Date: 2016-11-07 01:15+0100\n"
"Last-Translator: Jean Sanchez <jean.sanchez.fr@gmail.com>\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.4\n"
"X-Generator: Poedit 1.8.11\n"

#: src/debug/tserver/abstract.py:331
msgid "Wing Debug Log File\n"
msgstr "Fichier de log de débogage de Wing\n"

#: src/debug/tserver/abstract.py:332
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Ce file peut être utilisé pour diagnostiquer les problèmes dans les routines "
"du débogueur\n"

#: src/debug/tserver/abstract.py:333
msgid "For help, contact support@wingware.com\n"
msgstr "Pour de l'aide, contactez support@wingware.com\n"

#: src/debug/tserver/abstract.py:338
msgid "Warning:  Log file does not exist:\n"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/abstract.py:340
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Avertissement : et ne peut pas être créé. Enregistrement désactivé.\n"

#: src/debug/tserver/abstract.py:343
msgid "Warning:  Log file is not a file:\n"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/abstract.py:345
msgid "Warning:  Logging disabled\n"
msgstr "Avertissement : Logging désactivé\n"

#: src/debug/tserver/dbginspect.py:54 src/debug/tserver/dbgserver.py:2906
#: src/debug/tserver/dbgutils.py:443 src/debug/tserver/dbgutils.py:463
msgid "(truncated)"
msgstr ""

#: src/debug/tserver/dbginspect.py:920 src/debug/tserver/dbgutils.py:451
#: src/debug/tserver/dbgutils.py:473 src/debug/tserver/dbgutils.py:2949
msgid "<opaque "
msgstr "<opaque "

#: src/debug/tserver/dbgserver.py:1176
msgid "<module>"
msgstr "<module>"

#: src/debug/tserver/dbgserver.py:1324
msgid "<error evaluating>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgserver.py:1897 src/debug/tserver/dbgserver.py:1935
msgid "<thread %i is running>"
msgstr "<la tâche %i est en cours>"

#: src/debug/tserver/dbgserver.py:1900 src/debug/tserver/dbgserver.py:1938
msgid "<invalid thread id %s or stack index %s>"
msgstr "<id de tâche %s ou index de pile %s invalide>"

#: src/debug/tserver/dbgserver.py:1902 src/debug/tserver/dbgserver.py:1940
msgid "<invalid stack frame>"
msgstr "<élément de pile invalide>"

#: src/debug/tserver/dbgserver.py:1968 src/debug/tserver/dbgserver.py:1997
msgid "<sys.modules does not exist>"
msgstr "<sys.modules n'existe pas>"

#: src/debug/tserver/dbgserver.py:1971 src/debug/tserver/dbgserver.py:2003
msgid "<error accessing sys.modules>"
msgstr "<erreur en accédant à sys.modules>"

#: src/debug/tserver/dbgserver.py:2000
msgid "<no longer exists"
msgstr "<n'existe plus "

#: src/debug/tserver/dbgserver.py:2048 src/debug/tserver/dbgserver.py:2101
msgid "<no longer exists>"
msgstr "<n'existe plus>"

#: src/debug/tserver/dbgserver.py:2079 src/debug/tserver/dbgserver.py:4106
msgid "<parent too large>"
msgstr "<parent trop large>"

#: src/debug/tserver/dbgserver.py:2081 src/debug/tserver/dbgserver.py:4108
msgid "<invalid parent type>"
msgstr "<type de parent invalide>"

#: src/debug/tserver/dbgserver.py:2091 src/debug/tserver/dbgserver.py:2543
msgid "<value not found>"
msgstr "<valuer non trouvée>"

#: src/debug/tserver/dbgserver.py:2531
msgid "<thread is running>"
msgstr "<tâche en cours>"

#: src/debug/tserver/dbgserver.py:2533
msgid "<invalid context>"
msgstr "<contexte invalide>"

#: src/debug/tserver/dbgserver.py:4114
msgid "<invalid path %s at pos=%i>"
msgstr "<chemin %s invalide à la position=%i>"

#: src/debug/tserver/dbgutils.py:150
msgid "<undefined>"
msgstr ""

#: src/debug/tserver/dbgutils.py:166
msgid "at"
msgstr ""

#: src/debug/tserver/dbgutils.py:174
msgid "dim=%sx%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:176
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:186 src/debug/tserver/dbgutils.py:2451
#, fuzzy
msgid "<error handling value>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgutils.py:188
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:196
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:216
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:233
#, fuzzy
msgid "<opaque"
msgstr "<opaque "

#: src/debug/tserver/dbgutils.py:465
msgid "<huge %s at %s; len=%i>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbgutils.py:653 src/debug/tserver/dbgutils.py:665
msgid ", pos "
msgstr ", position "

#: src/debug/tserver/dbgutils.py:669
msgid ", line "
msgstr ", ligne "

#: src/debug/tserver/dbgutils.py:671
msgid "SyntaxError: "
msgstr "Erreur de syntaxe : "

#: src/debug/tserver/dbgutils.py:699
msgid "Error"
msgstr "Erreur"

#: src/debug/tserver/dbgutils.py:707
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Erreur : Wing n'a pas été capable de générer un message d'exception"

#: src/debug/tserver/dbgutils.py:3258 src/debug/tserver/dbgutils.py:3274
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3258 src/debug/tserver/dbgutils.py:3274
msgid "Value"
msgstr ""

#: src/debug/tserver/dbgutils.py:3269 src/debug/tserver/dbgutils.py:3296
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:459
msgid "Redirected I/O failed on closed debug connection"
msgstr ""
"La redirection des E/S a échoué lors de la fermeture de la connexion de "
"débogage"

#: src/debug/tserver/netserver.py:613
msgid "EOF when reading a line"
msgstr "EOF lors de la lecture d'une ligne"

#: src/debug/tserver/netserver.py:1110
msgid "(unavailable)"
msgstr "(indisponible)"

#: src/debug/tserver/netserver.py:1366
msgid "[omitting some output]"
msgstr "[omet quelques sorties]"

#: src/debug/tserver/startdebug.py:195 src/debug/tserver/startdebug.py:373
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/startdebug.py:199 src/debug/tserver/startdebug.py:377
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/startdebug.py:426
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:427
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:428
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:442
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:464
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:475
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:635
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:636
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:637
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:717 src/debug/tserver/startdebug.py:719
msgid "-- Type return or enter to exit --\n"
msgstr ""

#~ msgid "<unknown type>"
#~ msgstr "<type inconnu>"

#~ msgid "Value too large to evaluate: "
#~ msgstr "Value trop grande pour être évaluée : "

#~ msgid "<invalid path registration>"
#~ msgstr "<enregistrement de chemin invalide>"

#~ msgid "Function"
#~ msgstr "Fonction"

#~ msgid "Method"
#~ msgstr "Méthode"

#, fuzzy
#~ msgid "Could not execute because an error occurred:\n"
#~ msgstr ""
#~ "Impossible de lancer le programme car il y a eu une erreur:\n"
#~ "\n"

#~ msgid "Error: Runtime exception occurred"
#~ msgstr "Erreur: Obtention d'une erreur d'exécution"

#~ msgid "Default User"
#~ msgstr "Utilisateur par défaut"
