# Module src_debug_tserver translation file for language=en
# Copyright (C) 2011 Wingware
# Wingware Python IDE -- www.wingware.com
#
msgid ""
msgstr ""
"Project-Id-Version: 4.0.1\n"
"POT-Creation-Date: 2018-08-23 14:17+EDT\n"
"PO-Revision-Date: 2011-03-30 22:09 EDT\n"
"Last-Translator: Wingware <support@wingware.com>\n"
"Language-Team: None\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: text/plain\n"
"Generated-By: pygettext.py 1.5\n"

#: src/debug/tserver/abstract.py:331
msgid "Wing Debug Log File\n"
msgstr ""

#: src/debug/tserver/abstract.py:332
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""

#: src/debug/tserver/abstract.py:333
msgid "For help, contact support@wingware.com\n"
msgstr ""

#: src/debug/tserver/abstract.py:338
msgid "Warning:  Log file does not exist:\n"
msgstr ""

#: src/debug/tserver/abstract.py:340
msgid "Warning:  and could not be created; logging disabled\n"
msgstr ""

#: src/debug/tserver/abstract.py:343
msgid "Warning:  Log file is not a file:\n"
msgstr ""

#: src/debug/tserver/abstract.py:345
msgid "Warning:  Logging disabled\n"
msgstr ""

#: src/debug/tserver/dbginspect.py:54 src/debug/tserver/dbgserver.py:2942
#: src/debug/tserver/dbgutils.py:487 src/debug/tserver/dbgutils.py:507
msgid "(truncated)"
msgstr ""

#: src/debug/tserver/dbginspect.py:910 src/debug/tserver/dbgutils.py:495
#: src/debug/tserver/dbgutils.py:517 src/debug/tserver/dbgutils.py:3069
msgid "<opaque "
msgstr ""

#: src/debug/tserver/dbgserver.py:1183
msgid "<module>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1331
msgid "<error evaluating>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1923 src/debug/tserver/dbgserver.py:1959
msgid "<thread %i is running>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1926 src/debug/tserver/dbgserver.py:1962
msgid "<invalid thread id %s or stack index %s>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1928 src/debug/tserver/dbgserver.py:1964
msgid "<invalid stack frame>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1992 src/debug/tserver/dbgserver.py:2021
msgid "<sys.modules does not exist>"
msgstr ""

#: src/debug/tserver/dbgserver.py:1995 src/debug/tserver/dbgserver.py:2027
msgid "<error accessing sys.modules>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2024
msgid "<no longer exists"
msgstr ""

#: src/debug/tserver/dbgserver.py:2072 src/debug/tserver/dbgserver.py:2125
msgid "<no longer exists>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2103 src/debug/tserver/dbgserver.py:4183
msgid "<parent too large>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2105 src/debug/tserver/dbgserver.py:4185
msgid "<invalid parent type>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2115 src/debug/tserver/dbgserver.py:2579
msgid "<value not found>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2567
msgid "<thread is running>"
msgstr ""

#: src/debug/tserver/dbgserver.py:2569
msgid "<invalid context>"
msgstr ""

#: src/debug/tserver/dbgserver.py:4191
msgid "<invalid path %s at pos=%i>"
msgstr ""

#: src/debug/tserver/dbgutils.py:151
msgid "<undefined>"
msgstr ""

#: src/debug/tserver/dbgutils.py:167
msgid "at"
msgstr ""

#: src/debug/tserver/dbgutils.py:177
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:187 src/debug/tserver/dbgutils.py:2571
msgid "<error handling value>"
msgstr ""

#: src/debug/tserver/dbgutils.py:189
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:197
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:217
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:234
msgid "<opaque"
msgstr ""

#: src/debug/tserver/dbgutils.py:509
msgid "<huge %s at %s; len=%i>"
msgstr ""

#: src/debug/tserver/dbgutils.py:697 src/debug/tserver/dbgutils.py:709
msgid ", pos "
msgstr ""

#: src/debug/tserver/dbgutils.py:713
msgid ", line "
msgstr ""

#: src/debug/tserver/dbgutils.py:715
msgid "SyntaxError: "
msgstr ""

#: src/debug/tserver/dbgutils.py:743
msgid "Error"
msgstr ""

#: src/debug/tserver/dbgutils.py:751
msgid "Error: Wing was unable to pack up an exception message"
msgstr ""

#: src/debug/tserver/dbgutils.py:3383 src/debug/tserver/dbgutils.py:3399
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3383 src/debug/tserver/dbgutils.py:3399
msgid "Value"
msgstr ""

#: src/debug/tserver/dbgutils.py:3394 src/debug/tserver/dbgutils.py:3421
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:459
msgid "Redirected I/O failed on closed debug connection"
msgstr ""

#: src/debug/tserver/netserver.py:613
msgid "EOF when reading a line"
msgstr ""

#: src/debug/tserver/netserver.py:1110
msgid "(unavailable)"
msgstr ""

#: src/debug/tserver/netserver.py:1366
msgid "[omitting some output]"
msgstr ""

#: src/debug/tserver/startdebug.py:195 src/debug/tserver/startdebug.py:373
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr ""

#: src/debug/tserver/startdebug.py:199 src/debug/tserver/startdebug.py:377
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr ""

#: src/debug/tserver/startdebug.py:426
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:427
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:428
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:442
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:464
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:475
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:635
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:636
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:637
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:717 src/debug/tserver/startdebug.py:719
msgid "-- Type return or enter to exit --\n"
msgstr ""
